stages:
  data_extraction:
    cmd: python src/stages/extract_data.py --config params.yaml
    deps:
      - src/stages/extract_data.py
    outs:
      - data/raw/raw_data.csv
    params:
      - data_load
  train:
    cmd: python src/stages/train.py --config params.yaml
    deps:
      - src/stages/train.py
      - data/raw/raw_data.csv
    outs:
      - models/cluster_pipeline.joblib
      - data/processed/X_transformed.csv
    params:
      - train
  evaluate:
    cmd: python src/stages/evaluate.py --config params.yaml
    deps:
      - src/stages/evaluate.py
      - data/processed/X_transformed.csv
    metrics:
      - reports/metrics.json:
          cache: false
    plots:
      - reports/clusters.png:
          cache: false