stages:
  data_extraction:
    cmd: python src/stages/extract_data.py --config params.yaml
    deps:
      - src/stages/extract_data.py
    outs:
      - data/raw/raw_data.csv
  train:
    cmd: python src/stages/train.py
    deps:
      - src/stages/train.py
      - data/raw/raw_data.csv
      