stages:
  data_extraction:
    cmd: python src/stages/extract_data.py --config params.yaml
    deps:
      - src/stages/extract_data.py
    outs:
      - data/raw/raw_data.csv
    params:
      - data_load
  train:
    cmd: python src/stages/train.py --config params.yaml
    deps:
      - src/stages/train.py
      - data/raw/raw_data.csv
    outs:
      - models/cluster_pipeline.joblib
    params:
      - train
