data_load:
  PATH: data/raw
  KAGGLE_USERNAME: arjunbhasin2013
  KAGGLE_DATASET_NAME: ccdata
  dataset_rename: raw_data.csv

train:
  imputation_method: median
  scaler_method: standard
  n_components: 2
  n_clusters: 3
  capping_method: iqr
  tail: both
  fold: 1.5
  transformed_data: data/processed/X_transformed.csv
evaluate:
  cluster_plot: reports/clusters.png
  metrics: reports/metrics.json
PIPELINE_PATH: ./models/cluster_pipeline.joblib
PARAMS_NAME: params.yaml
DATA_PATH: ./data/raw/CC GENERAL.csv
INDEX_COL: CUST_ID
