imputation_method: mean
scaler_method: minmax
n_components: 2
n_clusters: 4
PIPELINE_PATH: ./models/cluster_pipeline.joblib'
PARAMS_NAME: params.yaml
DATA_PATH: ./data/raw/CC GENERAL.csv
INDEX_COL: CUST_ID